### ISSUE TITLE
Create infrastructure and scripts for releasing controller

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/prow-pipeline-controller#7]
@wbrefvem, in terms of release artefacts, what do we need? I would think we just need to create and release the Docker image, right? No need for a Helm chart.

AFAIU, how Prow comes together as a whole is defined here - https://github.com/jenkins-x-charts/prow/blob/master/prow/values.yaml#L238.

**Comment by wbrefvem** [comment]
@hferentschik sorry, just saw this. That's correct, no chart needed.
